// ─────────────────────────────────────────────
// WRAITH · modules/ppt.js
// .ppt <topic> — slides from DuckDuckGo free AI
// ─────────────────────────────────────────────
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

async function fetchDuckDuckGoBullets(topic, total = 20) {
  const prompt =
    `Give me exactly ${total} short factual presentation bullet points about "${topic}". ` +
    `Return ONLY the bullet points, one per line. No numbering, no markdown, no extra text.`;

  const models = [
    'gpt-4o-mini',
    'claude-3-haiku',
    'meta-llama/Llama-3-70b-chat-hf',
    'mistralai/Mixtral-8x7B-Instruct-v0.1'
  ];

  let lastErr;

  for (const model of models) {
    try {
      const vqdRes = await fetch('https://duckduckgo.com/duckchat/v1/status', {
        headers: { 'x-vqd-accept': '1', 'User-Agent': 'Mozilla/5.0' }
      });
      const vqd = vqdRes.headers.get('x-vqd-4');
      if (!vqd) throw new Error('No vqd token');

      const chatRes = await fetch('https://duckduckgo.com/duckchat/v1/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-vqd-4': vqd,
          'User-Agent': 'Mozilla/5.0'
        },
        body: JSON.stringify({
          model,
          messages: [{ role: 'user', content: prompt }]
        })
      });

      if (!chatRes.ok) throw new Error(`DDG ${chatRes.status}`);
      const text = await chatRes.text();

      const parts = [];
      for (const line of text.split('\n')) {
        const t = line.trim();
        if (!t.startsWith('data:')) continue;
        const payload = t.slice(5).trim();
        if (!payload || payload === '[DONE]') continue;
        try {
          const j = JSON.parse(payload);
          if (j.message) parts.push(j.message);
        } catch {}
      }

      const raw = parts.join('').trim();
      if (!raw) throw new Error('Empty DDG reply');

      const bullets = raw
        .split('\n')
        .map((l) => l.replace(/^[\-\*\u2022\d\.\)\s]+/, '').trim())
        .filter((l) => l.length > 3)
        .slice(0, total);

      if (!bullets.length) throw new Error('No bullets parsed');
      return bullets;

    } catch (e) {
      lastErr = e;
      console.warn(`[ppt] DDG model ${model} failed:`, e.message);
    }
  }

  throw lastErr || new Error('DuckDuckGo AI unavailable');
}

export async function pptCommand(sock, chat, msg, args) {
  const topic = (args || []).join(' ').trim();
  if (!topic) {
    return sock.sendMessage(chat, { text: '📊 *ppt*\n\nUsage: `.ppt <topic>`' }, { quoted: msg });
  }

  const status = await sock.sendMessage(chat, {
    text: `📊 *Building presentation on* ${topic}…`
  }, { quoted: msg });

  try {
    await sock.sendMessage(chat, {
      text: `📊 *Fetching content…*`,
      edit: status.key
    }).catch(() => {});

    const bullets = await fetchDuckDuckGoBullets(topic, 20);
    if (!bullets.length) throw new Error('No content returned');

    // ─── Load pptxgenjs (CJS) ───
    let PptxGenJS;
    try {
      const mod = require('pptxgenjs');
      PptxGenJS = mod?.default || mod;
    } catch {
      throw new Error('pptxgenjs not installed');
    }

    const safeName = topic.replace(/[^\w\s-]/g, '').trim().slice(0, 40) || 'presentation';

    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_WIDE';
    pptx.title = topic;

    // Title slide
    const s1 = pptx.addSlide();
    s1.background = { color: '1a1a2e' };
    s1.addText(topic, {
      x: 0.5, y: 1.9, w: 12, h: 1.4,
      fontSize: 36, bold: true, align: 'center', color: 'FFFFFF'
    });
    s1.addText('Generated by WRAITH', {
      x: 0.5, y: 3.5, w: 12, h: 0.5,
      fontSize: 14, align: 'center', color: 'AAAAAA'
    });

    // Content slides — 4 bullets per slide
    for (let i = 0; i < bullets.length; i += 4) {
      const slide = pptx.addSlide();
      slide.background = { color: 'FFFFFF' };
      slide.addText(`${topic}`, {
        x: 0.5, y: 0.3, w: 12, h: 0.7,
        fontSize: 22, bold: true, color: '1a1a2e'
      });
      slide.addText(
        bullets.slice(i, i + 4).map((b) => ({
          text: b,
          options: { bullet: true, breakLine: true }
        })),
        {
          x: 0.6, y: 1.2, w: 11.8, h: 5,
          fontSize: 15, color: '333333', lineSpacing: 22
        }
      );
    }

    const total = Math.ceil(bullets.length / 4) + 1;
    const dest = path.join(os.tmpdir(), `wraith-ppt-${Date.now()}.pptx`);
    await pptx.writeFile({ fileName: dest });

    await sock.sendMessage(chat, {
      document: fs.readFileSync(dest),
      fileName: `${safeName}.pptx`,
      mimetype: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      caption: `📊 *${topic}* — ${total} slides\n_Source: DuckDuckGo AI_`
    }, { quoted: msg });

    try { fs.unlinkSync(dest); } catch {}

    await sock.sendMessage(chat, {
      text: `✅ *Done*`,
      edit: status.key
    }).catch(() => {});

  } catch (e) {
    console.error('[ppt]', e.message);
    await sock.sendMessage(chat, {
      text: `❌ *PPT failed:* ${e.message}`,
      edit: status.key
    }).catch(() => {});
  }
}
